### ISSUE TITLE
Java error when installing in Liferay 6.2 GA4

### ISSUE THREAD

**Issue by JohnFinalist** [danielreuther/chroma-theme#7]
When installing chroma theme from the Liferay market-place I get the stackdump below. In the settings I can no longer switch to other default color layouts (red and green).

12:32:47,902 INFO  [http-bio-8080-exec-12][ThemeAutoDeployListener:51] Copying themes for /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247876/chroma-theme-6.2.0.1.war
12:32:47,915 INFO  [http-bio-8080-exec-12][BaseDeployer:863] Deploying chroma-theme-6.2.0.1.war
  Expanding: /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247876/chroma-theme-6.2.0.1.war into /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247916
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247916/WEB-INF
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247916/WEB-INF/classes
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247916/WEB-INF/classes
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247916/WEB-INF
12:32:48,206 INFO  [http-bio-8080-exec-12][BaseDeployer:2391] Modifying Servlet 2.4 /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247916/WEB-INF/web.xml
  Copying 751 files to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/webapps/chroma-theme
  Copied 78 empty directories to 4 empty directories under /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/webapps/chroma-theme
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/webapps/chroma-theme
  Deleting directory /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247916
12:32:48,575 INFO  [http-bio-8080-exec-12][ThemeAutoDeployListener:57] Themes for /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247876/chroma-theme-6.2.0.1.war copied successfully. Deployment will start in a few seconds.
12:32:48,582 INFO  [http-bio-8080-exec-12][WebAutoDeployListener:50] Copying web plugin for /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247876/resources-importer-web-6.2.0.4.war
12:32:48,591 INFO  [http-bio-8080-exec-12][BaseDeployer:863] Deploying resources-importer-web-6.2.0.4.war
12:32:48,594 INFO  [http-bio-8080-exec-12][BaseDeployer:966] Updating Resources Importer from version 6.2.0.4 to version 6.2.0.4
  Expanding: /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247876/resources-importer-web-6.2.0.4.war into /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123248595
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123248595/WEB-INF
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123248595/WEB-INF/classes
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123248595/WEB-INF/classes
12:32:48,658 INFO  [http-bio-8080-exec-12][BaseDeployer:2391] Modifying Servlet 2.4 /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123248595/WEB-INF/web.xml
  Copying 46 files to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/webapps/resources-importer-web
  Copying 1 file to /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/webapps/resources-importer-web
  Deleting directory /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123248595
12:32:48,692 INFO  [http-bio-8080-exec-12][WebAutoDeployListener:56] Web plugin for /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/temp/20150623123247876/resources-importer-web-6.2.0.4.war copied successfully. Deployment will start in a few seconds.
Jun 23, 2015 12:32:52 PM org.apache.catalina.startup.HostConfig deleteRedeployResources
INFO: Undeploying context [/resources-importer-web]
12:32:52,390 INFO  [ContainerBackgroundProcessor[StandardEngine[Catalina]]][HotDeployEvent:145] Plugin resources-importer-web requires marketplace-portlet
12:32:52,394 INFO  [ContainerBackgroundProcessor[StandardEngine[Catalina]]][HookHotDeployListener:952] Hook for resources-importer-web was unregistered
Jun 23, 2015 12:32:52 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
12:32:52,396 INFO  [ContainerBackgroundProcessor[StandardEngine[Catalina]]][PluginPackageUtil:1016] Reading plugin package for resources-importer-web
Jun 23, 2015 12:32:52 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/webapps/resources-importer-web
12:32:53,589 INFO  [localhost-startStop-2][HotDeployEvent:145] Plugin resources-importer-web requires marketplace-portlet
12:32:53,589 INFO  [localhost-startStop-2][HotDeployImpl:217] Deploying resources-importer-web from queue
12:32:53,590 INFO  [localhost-startStop-2][PluginPackageUtil:1016] Reading plugin package for resources-importer-web
Jun 23, 2015 12:32:53 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
12:32:53,749 INFO  [localhost-startStop-2][HookHotDeployListener:693] Registering hook for resources-importer-web
12:32:53,753 INFO  [localhost-startStop-2][HookHotDeployListener:821] Hook for resources-importer-web is available for use
Jun 23, 2015 12:32:53 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /home/finalist/Liferay/liferay-portal-6.2-ce-ga4/tomcat-7.0.42/webapps/chroma-theme
12:32:54,466 INFO  [localhost-startStop-2][HotDeployEvent:145] Plugin chroma-theme requires marketplace-portlet, resources-importer-web
12:32:54,466 INFO  [localhost-startStop-2][HotDeployImpl:217] Deploying chroma-theme from queue
12:32:54,467 INFO  [localhost-startStop-2][PluginPackageUtil:1016] Reading plugin package for chroma-theme
Jun 23, 2015 12:32:54 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
12:32:54,589 INFO  [localhost-startStop-2][HookHotDeployListener:693] Registering hook for chroma-theme
12:32:54,593 INFO  [localhost-startStop-2][HookHotDeployListener:821] Hook for chroma-theme is available for use
12:32:54,594 INFO  [localhost-startStop-2][ThemeHotDeployListener:98] Registering themes for chroma-theme
12:32:56,514 INFO  [localhost-startStop-2][ThemeHotDeployListener:113] 1 theme for chroma-theme is available for use
12:32:56,946 WARN  [liferay/hot_deploy-1][FileSystemImporter:469] Unable to import DDM structure Carousel
com.liferay.portlet.dynamicdatamapping.StructureNameException
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.validate(DDMStructureLocalServiceImpl.java:1770)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.validate(DDMStructureLocalServiceImpl.java:1802)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.validate(DDMStructureLocalServiceImpl.java:1760)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.addStructure(DDMStructureLocalServiceImpl.java:158)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.addStructure(DDMStructureLocalServiceImpl.java:284)
    at sun.reflect.GeneratedMethodAccessor1170.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:115)
    at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:62)
    at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:51)
    at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:111)
    at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:175)
    at com.sun.proxy.$Proxy214.addStructure(Unknown Source)
    at com.liferay.portlet.dynamicdatamapping.service.DDMStructureLocalServiceUtil.addStructure(DDMStructureLocalServiceUtil.java:606)
    at com.liferay.resourcesimporter.util.FileSystemImporter.addDDMStructures(FileSystemImporter.java:441)
    at com.liferay.resourcesimporter.util.ResourceImporter.addDDMStructures(ResourceImporter.java:212)
    at com.liferay.resourcesimporter.util.FileSystemImporter.setUpAssets(FileSystemImporter.java:1665)
    at com.liferay.resourcesimporter.util.FileSystemImporter.doImportResources(FileSystemImporter.java:1264)
    at com.liferay.resourcesimporter.util.ResourceImporter.importResources(ResourceImporter.java:47)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.importResources(ResourcesImporterHotDeployMessageListener.java:124)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.initialize(ResourcesImporterHotDeployMessageListener.java:73)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.onDeploy(ResourcesImporterHotDeployMessageListener.java:86)
    at com.liferay.portal.kernel.messaging.HotDeployMessageListener.doReceive(HotDeployMessageListener.java:55)
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
    at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:72)
    at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:65)
    at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:682)
    at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:593)
    at java.lang.Thread.run(Thread.java:745)
12:32:56,949 ERROR [liferay/hot_deploy-1][SerialDestination:68] Unable to process message {destinationName=liferay/hot_deploy, response=null, responseDestinationName=null, responseId=null, payload=null, values={groupId=0, command=deploy, companyId=0, servletContextName=chroma-theme}}
com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.portlet.dynamicdatamapping.StructureNameException
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
    at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:72)
    at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:65)
    at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:682)
    at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:593)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.liferay.portlet.dynamicdatamapping.StructureNameException
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.validate(DDMStructureLocalServiceImpl.java:1770)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.validate(DDMStructureLocalServiceImpl.java:1802)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.validate(DDMStructureLocalServiceImpl.java:1760)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.addStructure(DDMStructureLocalServiceImpl.java:158)
    at com.liferay.portlet.dynamicdatamapping.service.impl.DDMStructureLocalServiceImpl.addStructure(DDMStructureLocalServiceImpl.java:284)
    at sun.reflect.GeneratedMethodAccessor1170.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:115)
    at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:62)
    at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:51)
    at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:111)
    at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:175)
    at com.sun.proxy.$Proxy214.addStructure(Unknown Source)
    at com.liferay.portlet.dynamicdatamapping.service.DDMStructureLocalServiceUtil.addStructure(DDMStructureLocalServiceUtil.java:606)
    at com.liferay.resourcesimporter.util.FileSystemImporter.addDDMStructures(FileSystemImporter.java:441)
    at com.liferay.resourcesimporter.util.ResourceImporter.addDDMStructures(ResourceImporter.java:212)
    at com.liferay.resourcesimporter.util.FileSystemImporter.setUpAssets(FileSystemImporter.java:1665)
    at com.liferay.resourcesimporter.util.FileSystemImporter.doImportResources(FileSystemImporter.java:1264)
    at com.liferay.resourcesimporter.util.ResourceImporter.importResources(ResourceImporter.java:47)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.importResources(ResourcesImporterHotDeployMessageListener.java:124)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.initialize(ResourcesImporterHotDeployMessageListener.java:73)
    at com.liferay.resourcesimporter.messaging.ResourcesImporterHotDeployMessageListener.onDeploy(ResourcesImporterHotDeployMessageListener.java:86)
    at com.liferay.portal.kernel.messaging.HotDeployMessageListener.doReceive(HotDeployMessageListener.java:55)
    at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
    ... 5 more

**Comment by danielreuther** [comment]
Thanks much for bringing this up!

The issue should be fixed by 701fa91bc94a4261749348755dbf92e475734bf5. I'll do my best to upload an updated version on the Marketplace soon.

**Comment by JohnFinalist** [comment]
Good job, thanks. I'll be the first to test it if it comes available in the Marketplace
